name: gen_iso
on: 
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Pacakges
        run: |
          sudo apt-get update
          sudo apt-get -y install squashfs-tools cpio tar gzip genisoimage xorriso advancecomp p7zip-full
          sudo apt-get clean

      - name: Run Script
        run: |
          sudo bash main.sh

      - name: Upload artifact
        uses: actions/upload-artifact@main
        with:
          name: tcl.iso
          path: /tmp/tcl.iso